### ISSUE TITLE
大端没转小端

### ISSUE THREAD

**Issue by hatrd** [RicheyJang/RJFireWall#1]
https://github.com/RicheyJang/RJFireWall/blob/f29b8e58aec75ee12c4566bd426990bfac0a0c3c/kernel_mod/helpers/log_helper.c#L82C51-L82C51
`log.len = header->tot_len - (header->ihl * 4);`
应该为
`log.len = ntohs(header->tot_len) - (header->ihl * 4);`

另外，这似乎只是个包过滤防火墙+快速检测，而不是状态检测防火墙。没有发现有 TCP 的 SYN, SYN/ACK, ACK相关状态机的部分。

**Comment by RicheyJang** [comment]
欢迎发起PR~
