### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by JustDoIt0910** [RicheyJang/RJFireWall#3]
您好，我想学习一下这个项目，想问一下在熟悉 c 和基本的 linux 网络编程的基础上，还需要了解哪些前置技术吗？

**Comment by RicheyJang** [comment]
还需要对Linux内核模块开发、Netfilter、Netlink等技术，以及链表、红黑树等基本数据结构有一定了解

**Comment by JustDoIt0910** [comment]
谢谢
